version: '3'

services:
  sycorax_service:
    container_name: sycorax-service
    build: .
    environment:
      APP_ENV: $APP_ENV
      APP_PORT: 8080
      APP_DEBUG: $APP_DEBUG
      RESOURCES_PATH: $RESOURCES_PATH
      GIN_MODE: $GIN_MODE
    ports:
      - "8080:8080"
    networks:
      - sycorax-network

volumes:
  sycorax-volume:
    driver: local

networks:
  sycorax-network:
    driver: bridge
    name: sycorax-network
    external: true
