version: '3'

services:
  sycorax-mongo-express:
    image: mongo-express
    container_name: sycorax-mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USERNAME:-sycorax}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD:-Sycorax@2023!}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD:  ${MONGODB_ROOT_PASSWORD:-toor}
    links:
      - sycorax-mongodb
    networks:
      - sycorax-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sycorax-mongodb:
    image: 'mongo'
    container_name: sycorax-mongodb
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-toor}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-sycorax}
    volumes:
      - sycorax-mongodb-volume:/data/db
    networks:
      - sycorax-network
    ports:
      - '27017:27017'
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  sycorax-mongodb-volume:
    driver: local

networks:
  sycorax-network:
    driver: bridge
    name: sycorax-network
    external: true
